spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dev_projeto_fatec_ecomerce;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=projeto_fatec
spring.datasource.password=##fatec##


spring.jpa.open-in-view=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring-boot-starter-validation

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl